-- 20260804 — CLAIM DA CONVERSA + ORDENAÇÃO PÓS-INSERT DAS MENSAGENS
--
-- Defeito de produção (medido em 2026-08-04): duas mensagens da mesma lead com
-- 1,7s de intervalo (texto + áudio) produziram DUAS invocações paralelas do
-- platform-sales-brain, entrelaçadas — a lead recebeu duas saudações, duas
-- explicações e a mesma pergunta final duas vezes, diferindo por uma vírgula.
-- Não havia NENHUMA serialização no arquivo (0 ocorrências de advisory lock /
-- FOR UPDATE / claim).
--
-- São dois defeitos distintos e esta migração dá o substrato para os dois:
--   corrida  → brain_claim_at/brain_claim_token: toda invocação tenta TOMAR a
--              conversa com UPDATE condicional + RETURNING (atômico); quem não
--              toma SAI. Com TTL, porque invocação que morre (OOM/timeout do
--              isolate) não pode travar a conversa para sempre.
--   rajada   → platform_crm_messages.seq: ordenação por estado que só existe
--              DEPOIS do INSERT. Nem created_at nem metadata.wa_timestamp servem
--              para saber "o que entrou no banco depois do meu snapshot":
--              wa_timestamp é o relógio do WhatsApp (mundo), e o áudio prova a
--              inversão — wa_timestamp 20:59:57, linha inserida ~12s depois,
--              porque a transcrição acontece antes de a linha existir.
--
-- ADITIVA POR CONSTRUÇÃO: só ADD COLUMN (nullable, sem NOT NULL) e CREATE INDEX.
-- Zero UPDATE, zero DELETE, zero DROP sobre dado existente.

-- ── 1) Claim da conversa ────────────────────────────────────────────────────
alter table public.platform_crm_conversations
  add column if not exists brain_claim_at    timestamptz,
  add column if not exists brain_claim_token text;

comment on column public.platform_crm_conversations.brain_claim_at is
  'platform-sales-brain: instante em que uma invocacao tomou a conversa. NULL = livre. '
  'Claim expirado (mais velho que AI_BRAIN_CLAIM_TTL_MS) e tomavel por outra invocacao — '
  'isolate que morre nao pode travar a lead para sempre.';

comment on column public.platform_crm_conversations.brain_claim_token is
  'platform-sales-brain: dono do claim atual (uuid por invocacao). O release so limpa quando '
  'o token confere — senao uma invocacao que estourou o TTL derrubaria o claim de quem assumiu.';

-- ── 2) Ordenação pós-insert das mensagens ───────────────────────────────────
-- IDENTITY (não created_at): valor atribuído pelo banco NO INSERT, estritamente
-- crescente. Serve à pergunta "entrou alguma coisa depois do que eu já respondi?",
-- que created_at (relógio de início da transação) e wa_timestamp (relógio do
-- WhatsApp) respondem errado.
-- As linhas existentes recebem valores na ordem física; isso é irrelevante porque
-- toda comparação é "> a marca d'água desta execução", e linha nova sempre recebe
-- valor maior que qualquer backfill.
alter table public.platform_crm_messages
  add column if not exists seq bigint generated by default as identity;

comment on column public.platform_crm_messages.seq is
  'Ordem de INSERT no banco (identity). NAO e ordem do mundo: created_at e o relogio da '
  'transacao e metadata.wa_timestamp e o relogio do WhatsApp — o audio entra na base ~12s '
  'depois do proprio wa_timestamp (transcricao). Use seq para decidir visibilidade/rajada.';

create index if not exists platform_crm_messages_conversation_seq_idx
  on public.platform_crm_messages (conversation_id, seq desc);
