import type { FormTheme } from '@/types/forms';

export type FormThemeCategory = 'messaging' | 'social' | 'generic';

export interface FormThemePreset {
  id: string;
  name: string;
  description: string;
  category: FormThemeCategory;
  theme: Partial<FormTheme>;
}

export const FORM_THEME_PRESETS: FormThemePreset[] = [
  {
    id: 'vendus',
    name: 'Vendus',
    description: 'Preto + verde neon, títulos em caixa alta',
    category: 'generic',
    theme: {
      primary_color: '#A3FF12',
      background_color: '#0A0A0A',
      text_color: '#FFFFFF',
      font_family: 'Inter',
      heading_font_family: 'Archivo Black',
      heading_weight: 'black',
      heading_transform: 'uppercase',
      heading_letter_spacing: 'tight',
      border_radius: 'lg',
      button_style: 'filled',
      progress_color: '#A3FF12',
    },
  },
  {
    id: 'inlead',
    name: 'inlead (padrão)',
    description: 'Tipografia Inter, indigo, fundo claro',
    category: 'generic',
    theme: {
      primary_color: '#6366F1',
      background_color: '#F5F3FF',
      text_color: '#0F172A',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      heading_weight: 'bold',
      heading_transform: 'none',
      heading_letter_spacing: 'tight',
      border_radius: 'lg',
      button_style: 'filled',
      progress_color: '#6366F1',
    },
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    description: 'Verde clássico, bolhas estilo WA',
    category: 'messaging',
    theme: {
      primary_color: '#25D366',
      background_color: '#ECE5DD',
      text_color: '#0B141A',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      heading_weight: 'semibold',
      heading_transform: 'none',
      heading_letter_spacing: 'normal',
      border_radius: 'xl',
      button_style: 'filled',
      progress_color: '#075E54',
    },
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Azul céu, bolhas suaves',
    category: 'messaging',
    theme: {
      primary_color: '#2AABEE',
      background_color: '#E7F4FB',
      text_color: '#0F172A',
      font_family: 'Roboto',
      heading_font_family: 'Roboto',
      heading_weight: 'medium',
      heading_transform: 'none',
      heading_letter_spacing: 'normal',
      border_radius: 'xl',
      button_style: 'filled',
      progress_color: '#2AABEE',
    },
  },
  {
    id: 'imessage',
    name: 'iMessage',
    description: 'Estética Apple, azul/cinza',
    category: 'messaging',
    theme: {
      primary_color: '#0A84FF',
      background_color: '#F2F2F7',
      text_color: '#1C1C1E',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      heading_weight: 'semibold',
      heading_transform: 'none',
      heading_letter_spacing: 'tight',
      border_radius: 'full',
      button_style: 'filled',
      progress_color: '#0A84FF',
    },
  },
  {
    id: 'messenger',
    name: 'Messenger',
    description: 'Azul Facebook, bolhas redondas',
    category: 'messaging',
    theme: {
      primary_color: '#0084FF',
      background_color: '#F0F2F5',
      text_color: '#050505',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      heading_weight: 'bold',
      heading_transform: 'none',
      heading_letter_spacing: 'normal',
      border_radius: 'full',
      button_style: 'filled',
      progress_color: '#0084FF',
    },
  },
  {
    id: 'instagram',
    name: 'Instagram',
    description: 'Gradiente vibrante laranja-rosa',
    category: 'social',
    theme: {
      primary_color: '#E1306C',
      background_color: '#FAFAFA',
      text_color: '#262626',
      font_family: 'Poppins',
      heading_font_family: 'Poppins',
      heading_weight: 'extrabold',
      heading_transform: 'none',
      heading_letter_spacing: 'tight',
      border_radius: 'xl',
      button_style: 'filled',
      progress_color: '#F77737',
    },
  },
  {
    id: 'stories',
    name: 'Stories',
    description: 'Dark mode, glass, vibrante',
    category: 'social',
    theme: {
      primary_color: '#EC4899',
      background_color: '#0F0F14',
      text_color: '#F8FAFC',
      font_family: 'Poppins',
      heading_font_family: 'Poppins',
      heading_weight: 'black',
      heading_transform: 'uppercase',
      heading_letter_spacing: 'tight',
      border_radius: 'xl',
      button_style: 'filled',
      progress_color: '#A855F7',
    },
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    description: 'Preto + ciano + magenta',
    category: 'social',
    theme: {
      primary_color: '#FE2C55',
      background_color: '#000000',
      text_color: '#FFFFFF',
      font_family: 'Inter',
      heading_font_family: 'Archivo Black',
      heading_weight: 'black',
      heading_transform: 'uppercase',
      heading_letter_spacing: 'tight',
      border_radius: 'lg',
      button_style: 'filled',
      progress_color: '#25F4EE',
    },
  },
  {
    id: 'light_clean',
    name: 'Light Clean',
    description: 'Limpo, branco, azul moderno',
    category: 'generic',
    theme: {
      primary_color: '#3B82F6',
      background_color: '#FFFFFF',
      text_color: '#0F172A',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      heading_weight: 'bold',
      heading_transform: 'none',
      heading_letter_spacing: 'tight',
      border_radius: 'lg',
      button_style: 'filled',
      progress_color: '#3B82F6',
    },
  },
  {
    id: 'dark_pro',
    name: 'Dark Pro',
    description: 'Fundo escuro, contraste alto',
    category: 'generic',
    theme: {
      primary_color: '#818CF8',
      background_color: '#0F172A',
      text_color: '#F1F5F9',
      font_family: 'Inter',
      heading_font_family: 'Space Grotesk',
      heading_weight: 'bold',
      heading_transform: 'none',
      heading_letter_spacing: 'tight',
      border_radius: 'lg',
      button_style: 'filled',
      progress_color: '#818CF8',
    },
  },
  {
    id: 'minimal_mono',
    name: 'Minimal Mono',
    description: 'Preto e branco, sem sombras',
    category: 'generic',
    theme: {
      primary_color: '#0A0A0A',
      background_color: '#FAFAFA',
      text_color: '#0A0A0A',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      heading_weight: 'extrabold',
      heading_transform: 'none',
      heading_letter_spacing: 'tighter',
      border_radius: 'md',
      button_style: 'filled',
      progress_color: '#0A0A0A',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Laranja vibrante para rosa',
    category: 'generic',
    theme: {
      primary_color: '#F97316',
      background_color: '#FFF7ED',
      text_color: '#431407',
      font_family: 'Poppins',
      heading_font_family: 'Poppins',
      heading_weight: 'extrabold',
      heading_transform: 'none',
      heading_letter_spacing: 'tight',
      border_radius: 'xl',
      button_style: 'filled',
      progress_color: '#EC4899',
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Azul marinho + dourado',
    category: 'generic',
    theme: {
      primary_color: '#1E3A8A',
      background_color: '#F8FAFC',
      text_color: '#0F172A',
      font_family: 'Inter',
      heading_font_family: 'Inter',
      heading_weight: 'bold',
      heading_transform: 'none',
      heading_letter_spacing: 'normal',
      border_radius: 'md',
      button_style: 'filled',
      progress_color: '#CA8A04',
    },
  },
];
